### ISSUE TITLE
SonarQube 5.5+ Does not work

### ISSUE THREAD

**Issue by RahulCh1** [astrebel/sonar-slack-notifier-plugin#1]
Hello, your plugin is great! But I have upgraded to 5.5 and the metrics among other things are null... 
![capture](https://cloud.githubusercontent.com/assets/17237819/15727651/ab3cf31a-281d-11e6-84a5-23afc99959f4.PNG)

Can you please fix this if possible?

Thank you!
Rahul

**Comment by b-ilic-levi9-com** [comment]
I have the same issue. SonarQube 5.5

**Comment by labsilva** [comment]
I can't seem to get it to work at all with SonarQube 6.0

**Comment by Jubblerbug** [comment]
Same issue for me as labsilva, it no longer seems to work with SonarQube 6.0.  @astrebel do you know where the logs are saved in sonar so I can try figuring out why?

**Comment by DerekDibblee** [comment]
Same issue with SonarQube 6.0. No notifications being posted on Slack at all. No logs visible. Any progress?

**Comment by john-yick** [comment]
I am seeing the same issues here it does not work on 6.0 and no logs

**Comment by kogitant** [comment]
Hi, I've developed this plugin further in https://github.com/kogitant/sonar-slack-notifier-plugin 
The current version requires SonarQube 6.1.

**Comment by astrebel** [comment]
This plugin will unfortunately not be continued. But as @kogitant  wrote in the previous comment you can go to his repository which works with SonarQube 6+.
